# Composer install
FROM composer:2.7 as composer

# Runtime stage
FROM php:8.1-fpm as runtime

RUN usermod -u 1000 www-data

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        zip \
        unzip \
        git \
        libzip-dev \
        zlib1g-dev \
        libpng-dev \
        libjpeg-dev \
        libfreetype6-dev \
        nodejs \
        npm \
        && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/

RUN docker-php-ext-install gd zip mysqli pdo pdo_mysql bcmath exif

COPY --from=composer /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY package.json package-lock.json ./

RUN npm install

COPY composer.json composer.lock ./

RUN composer update --no-scripts --no-interaction --prefer-dist --optimize-autoloader

COPY . .

RUN composer dump-autoload --optimize

RUN php artisan storage:link

