<?php

namespace App\Models\Admin\SiteContent;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AboutUsPage extends Model
{
    use HasFactory;
    protected $fillable = [
        'Location',
        'Image',
        'Icon_One',
        'Icon_Two',
        'Icon_Three',
        'Icon_Four',
        'en_Title_One',
        'en_Title_Two',
        'en_Title_Three',
        'en_Title_Four',
        'en_Title',
        'en_Subtitle',
        'en_Description_One',
        'en_Description_Two',
        'en_Description_Three',
        'en_Description_Four',
        'fr_Title_One',
        'fr_Title_Two',
        'fr_Title_Three',
        'fr_Title_Four',
        'fr_Title',
        'fr_Subtitle',
        'fr_Description_One',
        'fr_Description_Two',
        'fr_Description_Three',
        'fr_Description_Four',
        'experience_years',
        'en_experience_text',
        'fr_experience_text',
        'en_vision_label',
        'fr_vision_label',
        'en_mission_label',
        'fr_mission_label',
        'en_values_title',
        'fr_values_title',
        'en_values_subtitle',
        'fr_values_subtitle',
        'en_value_one_title',
        'fr_value_one_title',
        'en_value_one_description',
        'fr_value_one_description',
        'en_value_two_title',
        'fr_value_two_title',
        'en_value_two_description',
        'fr_value_two_description',
        'en_value_three_title',
        'fr_value_three_title',
        'en_value_three_description',
        'fr_value_three_description',
        'en_value_four_title',
        'fr_value_four_title',
        'en_value_four_description',
        'fr_value_four_description',
        'en_why_title',
        'fr_why_title',
        'en_why_subtitle',
        'fr_why_subtitle',
        'en_why_item_one',
        'fr_why_item_one',
        'en_why_item_two',
        'fr_why_item_two',
        'en_why_item_three',
        'fr_why_item_three',
        'en_cta_title',
        'fr_cta_title',
        'en_cta_btn_crops',
        'fr_cta_btn_crops',
        'en_cta_btn_expert',
        'fr_cta_btn_expert',
        'why_image_one',
        'why_image_two',
    ];
}
